### ISSUE TITLE
Locking problem when using SchematronResourceSCH

### ISSUE THREAD

**Issue by costas80** [phax/ph-schematron#117]
Hi @phax ,

Came across an issue that is potentially a bug in class SchematronResourceSCH. I am testing using the [eInvoicing schematrons for UBL](https://github.com/ConnectingEurope/eInvoicing-EN16931) and specifically the SCH version of these.

Testing a sample using the SchematronResourcePure implementation work fine and returns the expected results. However, when I switch to using the SchematronResourceSCH implementation the process gets stuck with a lock. The code I use is quite trivial as follows:
```
var sampleFile = Path.of("path/to/a.xml");
var schematronFile = Path.of("path/to/EN16931-UBL-validation.sch");
var schematron = SchematronResourcePure.fromFile(schematronFile.toFile()); // This works
// var schematron = SchematronResourceSCH.fromFile(schematronFile.toFile()); // When using this the process locks
var result = schematron.applySchematronValidationToSVRL(new StreamSource(Files.newInputStream(sampleFile)));
```
Taking a thread dump I see the following:
```
   java.lang.Thread.State: RUNNABLE
	at net.sf.saxon.dom.DOMNodeWrapper.getSuccessorElement(DOMNodeWrapper.java:917)
	- locked <0x0000000702449538> (a com.sun.org.apache.xerces.internal.dom.DocumentImpl)
	at net.sf.saxon.dom.DOMNodeWrapper.getSuccessorElement(DOMNodeWrapper.java:44)
	at net.sf.saxon.tree.util.SteppingNavigator$FollowingElementStepper.step(SteppingNavigator.java:160)
	at net.sf.saxon.tree.util.SteppingNavigator$DescendantAxisIterator.next(SteppingNavigator.java:270)
	at net.sf.saxon.tree.util.SteppingNavigator$DescendantAxisIterator.next(SteppingNavigator.java:201)
        ...
	at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:360)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:349)
	- locked <0x0000000709703530> (a net.sf.saxon.s9api.XsltTransformer)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:74)
	at com.helger.schematron.sch.SchematronProviderXSLTFromSCH.<init>(SchematronProviderXSLTFromSCH.java:162)
```
Could this be an issue with SchematronResourceSCH or is it potentially a problem with the schematron files themselves? In terms of version, I'm using **6.0.3**. Thanks!

**Comment by phax** [comment]
It's not a lock - it just takes forever (~15-30 minutest).
That's why you precompile SCH to XSLT.
You might by the way be interested in my [phive project](https://github.com/phax/phive) which is a more generic validation engine and at [phive-rules](https://github.com/phax/phive-rules/) you find predefined rules  that are already optimized for speed etc.

**Comment by costas80** [comment]
Ah good to know! I'll check out the project you mention. Thanks for the fast reaction!
