### ISSUE TITLE
SAXParseException;  Premature end of file.

### ISSUE THREAD

**Issue by kal99** [phax/ph-schematron#14]
Hi 

I have a strange exception whereby by code runs fine in ubuntu/eclipse but fails in Windows 7 command line with the exception below. 

2015-11-27 13:37:08.0537 DEBUG main lang.ServiceLoaderHelper:156 - Finished retrieving all 2 SPI implementations of interface com.helger.commons.hashcode.IHashCodeImplementationRegistrarSPI
2015-11-27 13:37:08.0543 DEBUG main hashcode.HashCodeImplementationRegistry:328- Reinitialized com.helger.commons.hashcode.HashCodeImplementationRegistry
2015-11-27 13:37:08.0546 DEBUG main hashcode.HashCodeImplementationRegistry:292- Found no hashCode implementation for class java.lang.String
2015-11-27 13:37:08.0556 ERROR main transform.LoggingTransformErrorListener:182- [fatal_error] (1:1): Transformation fatal error (net.sf.saxon.trans.XPathException: Error reported by XML parser)
Exception in thread "main" net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
        at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:460)
        at net.sf.saxon.event.Sender.send(Sender.java:171)
        at net.sf.saxon.Controller.transform(Controller.java:1691)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:547)
        at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:177)
        at com.helger.schematron.xslt.AbstractSchematronXSLTBasedResource.applySchematronValidation(AbstractSchematronXSLTBasedResource.java:270)
        at com.helger.schematron.xslt.AbstractSchematronXSLTBasedResource.applySchematronValidation(AbstractSchematronXSLTBasedResource.java:214)
        at com.emerald.integration.validation.service.rules.SchematronValidationRuleTestApp.validateXMLViaXSLTSchematronDoc(SchematronValidationRuleTestApp.java:67)

Thanks.

**Comment by phax** [comment]
Hi!
Can you please post the source XML that is going to be validated.
Is it maybe an encoding problem???
// Philip

**Comment by kal99** [comment]
HI,

Looks like an encoding problem or stream pointer problem. I am going to debug tomorrow but in mean time here is the source document.

[article.txt](https://github.com/phax/ph-schematron/files/45896/article.txt)

**Comment by phax** [comment]
The problem might be, that the DTD cannot be found. Try validating a version without the DTD please.

**Comment by phax** [comment]
So did you manage to find the source of the error?

**Comment by kal99** [comment]
Hi, Been side-tracked on to something else so npt had a chance yet but will get back to you soon.

**Comment by kal99** [comment]
Apologies, should have updated the ticket. The problem was resolved by reinstalling the libraries and copying the dtd and the xml file over to the windows 7 machine again. Not sure that the actual underlying problem was, but it seemed to resolve it!

Kind Regards

Khalil Rehman
Software Developer | Emerald Group Publishing
Tel: +44 (0)1274 785291 | E-mail: krehman@emeraldinsight.com<mailto:krehman@emeraldinsight.com>
www.emeraldgrouppublishing.com<http://www.emeraldgrouppublishing.com/> | www.emeraldinsight.com<http://www.emeraldinsight.com/>

[Description: twitter-bird-white-on-blue-png]Follow us on Twitter<http://www.twitter.com/emeraldglobal>
[Description: facebook_logo]Like us on Facebook<http://www.facebook.com/emeraldgrouppublishing>

P Please consider the environment before printing this email

**Comment by phax** [comment]
Excellent - glad you could solve the problem :)
Since there was no update for a long time I simply decided to close it....
