### ISSUE TITLE
Is it possible to use an UNC path to a schematron file?

### ISSUE THREAD

**Issue by R00dRallec** [phax/ph-schematron#4]
Im am providing the following path: \\UNC\Path\R0004.sch and im getting the following exception:

Exception in thread "Thread-1" java.lang.RuntimeException: com.helger.schematron.pure.exchange.SchematronReadException: C:\UNC\Path\R0004.sch: Failed to resolve includes in resource [file=\UNC\Path\R0004.sch]
	at com.helger.schematron.pure.bound.PSBoundSchemaCache.getValueToCache(PSBoundSchemaCache.java:79)
	at com.helger.schematron.pure.bound.PSBoundSchemaCache.getValueToCache(PSBoundSchemaCache.java:38)
	at com.helger.commons.cache.AbstractNotifyingCache.getFromCache(AbstractNotifyingCache.java:78)
	at com.helger.schematron.pure.SchematronResourcePure.getBoundSchema(SchematronResourcePure.java:81)
	at com.helger.schematron.pure.SchematronResourcePure.isValidSchematron(SchematronResourcePure.java:86)
	at com.validator.utils.ValidationController.performTests(ValidationController.java:291)
	at com.validator.utils.ValidationController.run(ValidationController.java:185)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.helger.schematron.pure.exchange.SchematronReadException: C:\UNC\Path\R0004.sch: Failed to resolve includes in resource [file=\UNC\Path\R0004.sch]
	at com.helger.schematron.pure.exchange.PSReader.readSchema(PSReader.java:1254)
	at com.helger.schematron.pure.bound.PSBoundSchemaCacheKey.readSchema(PSBoundSchemaCacheKey.java:108)
	at com.helger.schematron.pure.bound.PSBoundSchemaCacheKey.createBoundSchema(PSBoundSchemaCacheKey.java:189)
	at com.helger.schematron.pure.bound.PSBoundSchemaCache.getValueToCache(PSBoundSchemaCache.java:74)
	... 7 more

**Comment by phax** [comment]
Can you please paste the Schematron example fragment?
If I recall correctly, UNC pathes start with double \\ - is this maybe an issue?

**Comment by R00dRallec** [comment]
Oh, my mistake, i forgot the second \.
So the UNC path i use is: \\UNC\Path\R0004.sch

The code snippet:

schRule is a File object, created with the unc path, and checked with schRule.exists() if the file is available.

final ISchematronResource aResPure = SchematronResourcePure.fromFile(schRule);
                if (!aResPure.isValidSchematron()) //Here is the error thrown
                    throw new Exception("Invalid Schematron!");

**Comment by phax** [comment]
This seems to be an issue in the include resolver.
So I need to know how the exact include-element used in the Schematron.
May be a resolve from basis "\\UNC\Path\R0004.sch" using a path does not work...

**Comment by phax** [comment]
There is a generic issue with UNC paths when they are converted to FileSystemResources - I will investigate this

**Comment by phax** [comment]
Are you able to check the trunk, or do you need a release?

**Comment by R00dRallec** [comment]
Release would be perfect. Thanks!

**Comment by phax** [comment]
ph-schematron 2.9.0 is on Maven Central, so issue should be resolved. Requires ph-commons 5.3.0

**Comment by phax** [comment]
So problem solved now?

**Comment by R00dRallec** [comment]
Yes! Thanks for the support.

**Comment by phax** [comment]
There is a 2.9.1 release which fixes a classloader issue in web applications
