### ISSUE TITLE
Support XML catalogs in Apache Ant Task

### ISSUE THREAD

**Issue by xephon2** [phax/ph-schematron#40]
It would be nice, if **ph-schematron** would support XML catalogs. It would be perfect, if it would use the common principle from the [`<xslt>` task](https://ant.apache.org/manual/Tasks/style.html).

```xml
<xslt basedir="doc" destdir="build/doc" extension=".html" style="style/apache.xsl">
  <xmlcatalog refid="mycatalog"/>
</xslt>

<xslt basedir="doc" destdir="build/doc" extension=".html" style="style/apache.xsl">
   <xmlcatalog>
       <dtd publicId="-//ArielPartners//DTD XML Article V1.0//EN"
         location="com/arielpartners/knowledgebase/dtd/article.dtd"/>
   </xmlcatalog>
</xslt>
```

This would be very important to, e.g., work with [DITA XML files](https://github.com/dita-ot/docs/tree/develop/samples), see grammar here: [org.oasis-open.dita.v1_3](https://github.com/dita-ot/dita-ot/tree/develop/src/main/plugins/org.oasis-open.dita.v1_3)

**Comment by phax** [comment]
Theoretically this is pretty straight forward but:
Currently I only have EntityResolver/UrlResolver only for the Schematron parsing but not for the XML to be validated :|
So this will need some time...

**Comment by xephon2** [comment]
Alright, I'll lean back and enjoy the show. 🍸 🏖

**Comment by phax** [comment]
Can you please check if `ant-apache-resolver.jar` is part of the default Ant setup. Thanks

**Comment by phax** [comment]
The next SNAPSHOT (after 14:41 UTC) should do the trick - please try than.
I tested with the following setup:
```xml
    <schematron schematronFile="test.sch" 
                expectSuccess="true"
                schematronProcessingEngine="pure">
      <fileset dir=".">
        <include name="test.xml" />
      </fileset>
      <xmlcatalog>
        <dtd publicId="-//bla//DTD XML test//EN" location="test.dtd"/>
      </xmlcatalog>
    </schematron>
```

**Comment by xephon2** [comment]
**build.xml**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." default="check">
  <loadproperties srcfile="test.properties"/>
  <!-- Create path -->
  <path id="phsch.path">
    <pathelement location="ph-schematron-ant-task-4.2.3-20170505.144759-8-jar-with-dependencies.jar"/>
    <pathelement location="resolver.jar"/>
  </path>
  <!--<xmlcatalog id="dita.catalog">
    <catalogpath path="../../.dita/dita-ot/catalog-dita.xml"/>
  </xmlcatalog>-->
  <!-- Define <schematron> task -->
  <taskdef name="schematron" classname="com.helger.schematron.ant.Schematron" classpathref="phsch.path" />
  <target name="check">
    <schematron schematronFile="test.sch" expectSuccess="true">
      <fileset dir=".">
        <include name="*.dita" />
      </fileset>
      <xmlcatalog>
        <dtd publicId="-//OASIS//DTD DITA Topic//EN" location="../../.dita/dita-ot/catalog-dita.xml"/>
      </xmlcatalog>
    </schematron>
  </target>
</project>
```

**Output**

```
check:
[schematron] Successfully parsed Schematron file 'C:\Users\eike\Desktop\ph-schematron\test.sch'
[schematron] Validating XML file 'C:\Users\eike\Desktop\ph-schematron\test.dita' against Schematron rules from 'test.sch' expecting success
[schematron] [main] ERROR com.helger.xml.sax.LoggingSAXErrorHandler - [fatal_error] @ file:/C:/Users/eike/.dita/dita-ot/catalog-dita.xml(7:5) [SAX] Die Markup-Deklarationen, die in der Dokumenttypdeklaration enthalten sind bzw. auf die von der Dokumenttypdeklaration verwiesen wird, müssen ordnungsgemäß formatiert sein. (org.xml.sax.SAXParseException: Die Markup-Deklarationen, die in der Dokumenttypdeklaration enthalten sind bzw. auf die von der Dokumenttypdeklaration verwiesen wird, müssen ordnungsgemäß formatiert sein.)
[schematron] [main] ERROR com.helger.commons.callback.exception.LoggingExceptionCallback - [error] @ file:/C:/Users/eike/.dita/dita-ot/catalog-dita.xml(7:5) [SAX] Die Markup-Deklarationen, die in der Dokumenttypdeklaration enthalten sind bzw. auf die von der Dokumenttypdeklaration verwiesen wird, müssen ordnungsgemäß formatiert sein. (org.xml.sax.SAXParseException: Die Markup-Deklarationen, die in der Dokumenttypdeklaration enthalten sind bzw. auf die von der Dokumenttypdeklaration verwiesen wird, müssen ordnungsgemäß formatiert sein.)
[schematron] org.xml.sax.SAXParseException; systemId: file:/C:/Users/eike/.dita/dita-ot/catalog-dita.xml; lineNumber: 7; columnNumber: 5; Die Markup-Deklarationen, die in der Dokumenttypdeklaration enthalten sind bzw. auf die von der Dokumenttypdeklaration verwiesen wird, müssen ordnungsgemäß formatiert sein.
[schematron] 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
[schematron] 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
[schematron] 	at com.helger.xml.serialize.read.DOMReader.readXMLDOM(DOMReader.java:331)
[schematron] 	at com.helger.xml.serialize.read.DOMReader.readXMLDOM(DOMReader.java:181)
[schematron] 	at com.helger.schematron.SchematronResourceHelper.getNodeOfSource(SchematronResourceHelper.java:119)
[schematron] 	at com.helger.schematron.AbstractSchematronResource.getAsNode(AbstractSchematronResource.java:166)
[schematron] 	at com.helger.schematron.AbstractSchematronResource.applySchematronValidationToSVRL(AbstractSchematronResource.java:243)
[schematron] 	at com.helger.schematron.ant.Schematron._performValidation(Schematron.java:288)
[schematron] 	at com.helger.schematron.ant.Schematron.execute(Schematron.java:449)
[schematron] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[schematron] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[schematron] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[schematron] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[schematron] 	at java.lang.reflect.Method.invoke(Unknown Source)
[schematron] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[schematron] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[schematron] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[schematron] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[schematron] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[schematron] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[schematron] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[schematron] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[schematron] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[schematron] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[schematron] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[schematron] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

BUILD FAILED
C:\Users\eike\Desktop\ph-schematron\build.xml:15: Exception validating XML 'C:\Users\eike\Desktop\ph-schematron\test.dita' against Schematron rules from 'test.sch'. Technical details: SAXParseException - Die Markup-Deklarationen, die in der Dokumenttypdeklaration enthalten sind bzw. auf die von der Dokumenttypdeklaration verwiesen wird, müssen ordnungsgemäß formatiert sein.
```

**Comment by phax** [comment]
So
> [error] @ file:/C:/Users/eike/.dita/dita-ot/catalog-dita.xml(7:5) [SAX] Die Markup-Deklarationen, die in der Dokumenttypdeklaration enthalten sind bzw. auf die von der Dokumenttypdeklaration verwiesen wird, müssen ordnungsgemäß formatiert sein. (org.xml.sax.SAXParseException: Die Markup-Deklarationen, die in der Dokumenttypdeklaration enthalten sind bzw. auf die von der Dokumenttypdeklaration verwiesen wird, müssen ordnungsgemäß formatiert sein.)
It's none of my business ;)

**Comment by xephon2** [comment]
I'll check that again, but I just pointed it to the DITA default. Could you please have a look at the syntax of my **build.xml**? Should this work?

**Comment by phax** [comment]
Looks good to me. I made the experience that the Java XML parser is quite strict... Maybe you can post the respective part of .dita/dita-ot/catalog-dita.xml(7:5)
Most likely I will continue responding on Monday :)

**Comment by xephon2** [comment]
This is the file [catalog.xml](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.oasis-open.dita.v1_3/catalog.xml)

I'll switch the machine and try again. Thank you for the work and have a nice weekend.

**Comment by phax** [comment]
> java.io.FileNotFoundException: C:\Users\eike\Desktop\ph-schematron\topic.dtd (Das System kann die angegebene Datei nicht finden)

Seems like the base path is not correct.
Is "resolver.jar" the same as "ant-apache-resolver.jar"?

**Comment by xephon2** [comment]
I could not get it to work until now on Apricity OS. Will investigate this later.

```bash
 stefan  ~  Schreibtisch  schematron-test  ls -l
insgesamt 19820
-rw-r--r-- 1 stefan stefan    9680 18. Apr 10:38 ant-apache-resolver-1.9.7.jar
-rw-r--r-- 1 stefan stefan     843  6. Mai 10:13 build.xml
-rw-r--r-- 1 stefan stefan 6739420  3. Mai 21:02 ph-schematron-ant-task-4.2.3-20170503.152827-6-jar-with-dependencies.jar
-rw-r--r-- 1 stefan stefan 6755712  4. Mai 21:39 ph-schematron-ant-task-4.2.3-20170504.155755-7-jar-with-dependencies.jar
-rw-r--r-- 1 stefan stefan 6756725  5. Mai 22:57 ph-schematron-ant-task-4.2.3-20170505.144759-8-jar-with-dependencies.jar
-rw-r--r-- 1 stefan stefan    8169  6. Mai 10:11 schematron-test.xpr
-rw-r--r-- 1 stefan stefan     267  4. Mai 21:46 test.dita
-rw-r--r-- 1 stefan stefan      31  6. Mai 10:07 test.properties
-rw-r--r-- 1 stefan stefan     394  3. Mai 21:06 test.sch
 stefan  ~  Schreibtisch  schematron-test  ant -lib "/home/stefan/Schreibtisch/schematron-test/ant-apache-resolver-1.9.7.jar" -lib "/home/stefan/Schreibtisch/schematron-test/ph-schematron-ant-task-4.2.3-20170505.144759-8-jar-with-dependencies.jar"
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-8-openjdk/lib/tools.jar
Buildfile: /home/stefan/Schreibtisch/schematron-test/build.xml

check:
[schematron] Successfully parsed Schematron file '/home/stefan/Schreibtisch/schematron-test/test.sch'
[schematron] Validating XML file '/home/stefan/Schreibtisch/schematron-test/test.dita' against Schematron rules from 'test.sch' expecting success
Warning: XML resolver not found; external catalogs will be ignored

BUILD SUCCESSFUL
Total time: 1 second
 stefan  ~  Schreibtisch  schematron-test  
```

**Comment by phax** [comment]
I added another test with a couple of directories but it all works fine.
Maybe you can try it again **without** any resolver JAR in the CP.
And btw. because of some incompatible changes in the base library I will change the version to 4.3.0
